Fix ordering of endpoints
getflip/swirl pull request #505
Opened 2024-01-04 15:03 UTC by fellmann

2024-01-08 11:17 UTC, webspaceadam requested changes
small improvements :)

2024-01-08 11:17 UTC, webspaceadam commented on apps/swirl-docs/src/scripts/prebuild.ts
> +} from "./DeploymentStrategy/NavigationGenerator";
i think the deployment strategy is now the wrong name. there once was the idea to only generate stuff for "prod" and for "staging". this is no longer the case so i think we can just go over the "Strategy" and call it generators directly

2024-01-08 11:17 UTC, webspaceadam commented on apps/swirl-docs/src/scripts/DeploymentStrategy/index.ts
> -import { FileFetcher } from "./FileFetcher";
this whole file now is unnecessary?

2024-01-09 10:05 UTC, fellmann commented on apps/swirl-docs/src/scripts/ApiDocumentation/EndpointMapper.ts
> +    // if (
this was deactivated because of an invalid spec, fixed by now.

2024-01-09 10:07 UTC, fellmann commented on apps/swirl-docs/src/scripts/DeploymentStrategy/ApiEndpointGenerator.ts
> +export const API_SPEC_PATH = path.resolve(`${process.cwd()}/specs`);
this does not work because of circular imports, it fails when api navigation is not yet generated.

2024-01-09 10:07 UTC, fellmann commented on apps/swirl-docs/src/scripts/DeploymentStrategy/NavigationGenerator.ts
> +export const API_DOCS_PATH = path.resolve(`${process.cwd()}/src/documents/api`);
same as above :)

2024-01-09 10:09 UTC, fellmann commented on apps/swirl-docs/src/scripts/DeploymentStrategy/NavigationGenerator.ts
> +        specName: api.id,
I think this is still used, for example in the Api Overview Tiles to link to the matching navigation item for an api?

2024-01-09 10:22 UTC, fellmann commented on apps/swirl-docs/src/scripts/DeploymentStrategy/index.ts
> -import { FileFetcher } from "./FileFetcher";
it's now used in prebuild.ts

2024-01-10 09:04 UTC, webspaceadam approved these changes
lgtm

2024-01-10 09:17 UTC, merged