APP-11796: a11y grid
getflip/swirl pull request #83
Opened 2022-11-08 11:02 UTC by webspaceadam

implemented custom dynamic refs hook, basic aria component for grid, refactored IconGrid to use Grid logic

## Summary

- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-11796)

## Review Checklist

### General

- [ ] [Changeset added](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md)
- [ ] The submitted code is organized and formatted according to our [💅 Style Guide](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-style-guide--page).
  - [ ] The code is formatted with Prettier.
  - [ ] There are no linting errors.

### For new or updated components

https://swirl-storybook.flip-app.dev/?path=/docs/contributions-merge-publish--page

- [ ] The changes do not contain any breaking changes.
- [ ] The changes do not introduce new components that don't belong in the library (e.g. non-reusable components, highly specialized components, components including business logic)
- [ ] The component documentation is updated.
- [ ] The changes meet the [🤖 testing requirements](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-testing--page).
  - [ ] New features are tested.
  - [ ] In case of bug fixes, regression tests have been added.
  - [ ] All tests are 🟢.
- [ ] The changes meet the [🧏‍♀️ accessibility requirements](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-accessibility--page).
  - [ ] WCAG 2.1 Level A and Level AA requirements are met.
  - [ ] The Storybook a11y addon shows no errors.
  - [ ] The changes have been tested with a screen reader.
  - [ ] Keyboard controls have been tested, if applicable.
  - [ ] Components implementing form controls (inputs, buttons, selects, etc.) do not use Shadow DOM, and instead use Stencil's scoping mechanism
- [ ] The changes use our [🌈 theming concept](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-theming--page).
  - [ ] Design tokens have been used where appropriate.
  - [ ] The component has been visually checked in combination with the "Light" and "Dark" theme.
- [ ] The changes meet our [🌍 internationalization requirements](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-internationalization--page).
  - [ ] No static text is used.
  - [ ] The component doesn't break with longer texts or different text wrappings.
  - [ ] Number, currency and date values can be formatted appropriately.
- [ ] The changes work in all supported browsers and viewports. See [📱 Responsive Design](https://swirl-storybook.flip-app.dev/?path=/docs/requirements-responsive-design--page)

2022-11-09 08:35 UTC, Sqrrl requested changes

2022-11-09 08:35 UTC, Sqrrl commented on apps/swirl-docs/src/components/Grid/index.tsx
> +    <div role="grid" aria-colcount={1} aria-rowcount={1}>
colcount and rowcount seem unnecessary, as all columns and rows are visible all the time.

2022-11-09 08:35 UTC, Sqrrl commented on apps/swirl-docs/src/lib/hooks/useDynamicRefs.ts
> +    case "ArrowRight" || "ArrowDown":
I don't think the || works here. ArrowDown does nothing. You can use:

```
case 'ArrowRight':
case 'ArrowDown':
```

2022-11-09 09:19 UTC, webspaceadam commented on apps/swirl-docs/src/pages/icons/components/IconGrid.tsx
> +            handleGridKeyDown(event.key, { data: iconList, index }, getRef)
The problem with document.activeElement here is that this component will be rendered statically and react does not let me use that out of the box. so this refs map is the react way of working with dom element manipulation. At least as far i know :D

2022-11-11 07:49 UTC, Sqrrl approved these changes

2022-11-11 15:51 UTC, merged